-- Trendyol Pro / Supabase
-- Supabase Dashboard > SQL Editor'da bir kez çalıştırın.

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    name text not null,
    aurl text not null,
    surl text not null,
    sku text,
    cost numeric(12,2) not null default 0,
    box numeric(12,2) not null default 0,
    ship numeric(12,2) not null default 0,
    comm numeric(6,2) not null default 0,
    tax numeric(6,2) not null default 0,
    stock integer not null default 0,
    sell numeric(12,2) not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists products_user_id_idx on public.products(user_id);

alter table public.products enable row level security;

drop policy if exists "products_select_own" on public.products;
create policy "products_select_own" on public.products
for select to authenticated using (auth.uid() = user_id);

drop policy if exists "products_insert_own" on public.products;
create policy "products_insert_own" on public.products
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "products_update_own" on public.products;
create policy "products_update_own" on public.products
for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "products_delete_own" on public.products;
create policy "products_delete_own" on public.products
for delete to authenticated using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

-- ÖNEMLİ:
-- GitHub Pages'e service_role/secret key koymayın.
-- Publishable/anon key frontend'de kullanılabilir; güvenliği RLS sağlar.
